INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يناير', 'سكني', 2772299780, 6720570, 4337);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يناير', 'تجاري', 3810875406, 7774811, 396);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يناير', 'زراعي', 188570148, 24522173, 343);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'فبراير', 'سكني', 3107495689, 3053794, 4610);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'فبراير', 'تجاري', 1220082003, 1781064, 365);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'فبراير', 'زراعي', 279577156, 28029776, 425);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'فبراير', 'صناعي', 2070403, 465, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مارس', 'سكني', 3246521599, 5039891, 5220);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مارس', 'تجاري', 706017190, 482925, 349);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مارس', 'زراعي', 126122035, 16737005, 333);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ابريل', 'سكني', 3684873564, 4059352, 5634);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ابريل', 'تجاري', 1036708290, 1942051, 350);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ابريل', 'زراعي', 123187652, 38134351, 454);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مايو', 'سكني', 3368534728, 4686502, 5136);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مايو', 'تجاري', 1361810996, 4379763, 402);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مايو', 'زراعي', 219726113, 44250565, 394);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'مايو', 'صناعي', 2500000, 465, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يونيو', 'سكني', 1089868121, 1892172, 1758);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يونيو', 'تجاري', 688365239, 2547082, 139);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يونيو', 'زراعي', 51604852, 6014732, 160);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يوليو', 'سكني', 2621517919, 4420356, 4595);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يوليو', 'تجاري', 1080647743, 764339, 362);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'يوليو', 'زراعي', 1049397289, 27282685, 360);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اوغسطس', 'سكني', 1265959418, 1919210, 2697);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اوغسطس', 'تجاري', 1034164342, 585949, 233);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اوغسطس', 'زراعي', 71201629, 21683767, 231);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'سبتمبر', 'سكني', 2077070386, 2828661, 4152);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'سبتمبر', 'تجاري', 474164528, 569242, 359);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'سبتمبر', 'زراعي', 67713601, 26916812, 282);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اكتوبر', 'سكني', 3214560020, 4446522, 6232);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اكتوبر', 'تجاري', 1438207165, 2545179, 448);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'اكتوبر', 'زراعي', 531184657, 39449060, 379);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'نوفمبر', 'سكني', 3347349309, 4307194, 6403);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'نوفمبر', 'تجاري', 3843501722, 9328370, 483);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'نوفمبر', 'زراعي', 230365815, 39104369, 274);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ديسمبر', 'سكني', 4754615069, 6350288, 8582);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ديسمبر', 'تجاري', 1408401447, 1391188, 552);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (1, 'منطقة الرياض', 'ديسمبر', 'زراعي', 506913375, 20151348, 220);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يناير', 'سكني', 1904567660, 1500771, 2581);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يناير', 'تجاري', 387048099, 215531, 217);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يناير', 'زراعي', 28594000, 1184010, 32);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'فبراير', 'سكني', 2033567950, 1405133, 2454);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'فبراير', 'تجاري', 440176500, 306384, 233);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'فبراير', 'زراعي', 16255676, 285380, 48);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مارس', 'سكني', 2128527097, 1507136, 2783);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مارس', 'تجاري', 269430576, 183735, 260);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مارس', 'زراعي', 8294275, 753780, 41);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ابريل', 'سكني', 2395966107, 1902097, 2813);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ابريل', 'تجاري', 479853088, 267641, 276);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ابريل', 'زراعي', 10682252, 419011, 18);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مايو', 'سكني', 1765915070, 1275925, 2210);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مايو', 'تجاري', 423183630, 234251, 231);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'مايو', 'زراعي', 92507000, 661641, 16);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يونيو', 'سكني', 2886861978, 394674, 747);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يونيو', 'تجاري', 1912670486, 3194129, 85);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يونيو', 'زراعي', 9700333, 53002, 5);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يوليو', 'سكني', 1722923329, 1565271, 2587);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يوليو', 'تجاري', 543156841, 525786, 254);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'يوليو', 'زراعي', 8320086, 133047, 22);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اوغسطس', 'سكني', 1151204349, 774391, 1392);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اوغسطس', 'تجاري', 632808406, 2168278, 158);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اوغسطس', 'زراعي', 30831000, 251342, 14);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'سبتمبر', 'سكني', 1731623628, 1263850, 2095);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'سبتمبر', 'تجاري', 859135941, 1395761, 201);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'سبتمبر', 'زراعي', 38977563, 1310112, 25);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اكتوبر', 'سكني', 2315533635, 1786155, 2916);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اكتوبر', 'تجاري', 592190772, 332655, 340);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'اكتوبر', 'زراعي', 17104865, 680357, 22);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'نوفمبر', 'سكني', 2218219493, 1770961, 3147);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'نوفمبر', 'تجاري', 488405374, 302140, 326);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'نوفمبر', 'زراعي', 122058138, 2220029, 21);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ديسمبر', 'سكني', 3854974450, 2275730, 4009);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ديسمبر', 'تجاري', 646013267, 393724, 437);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (2, 'منطقة مكة المكرمة', 'ديسمبر', 'زراعي', 3430000, 855963, 15);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يناير', 'سكني', 580265431, 618112, 722);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يناير', 'تجاري', 144755715, 157345, 141);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يناير', 'زراعي', 26677198, 1860709, 62);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'فبراير', 'سكني', 593444361, 755638, 965);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'فبراير', 'تجاري', 555428630, 109978, 102);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'فبراير', 'زراعي', 15024000, 1914234, 77);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مارس', 'سكني', 484673364, 492371, 815);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مارس', 'تجاري', 177077101, 1154154, 90);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مارس', 'زراعي', 15542925, 720793, 52);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ابريل', 'سكني', 493679303, 548127, 752);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ابريل', 'تجاري', 374311007, 98256, 82);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ابريل', 'زراعي', 13355772, 743476, 41);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مايو', 'سكني', 364366484, 342715, 622);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مايو', 'تجاري', 75033633, 93914, 72);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'مايو', 'زراعي', 83336232, 770839, 76);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يونيو', 'سكني', 214030775, 197515, 255);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يونيو', 'تجاري', 16048164, 23106, 34);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يونيو', 'زراعي', 13239000, 1295009, 17);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يوليو', 'سكني', 413006709, 721567, 693);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يوليو', 'تجاري', 101375521, 74198, 106);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'يوليو', 'زراعي', 17702567, 1041623, 36);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اوغسطس', 'سكني', 237572431, 299537, 492);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اوغسطس', 'تجاري', 49884779, 59827, 74);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اوغسطس', 'زراعي', 3183000, 393312, 23);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'سبتمبر', 'سكني', 425698268, 526999, 770);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'سبتمبر', 'تجاري', 193665317, 63716, 76);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'سبتمبر', 'زراعي', 33929800, 1609273, 45);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اكتوبر', 'سكني', 505598445, 501929, 872);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اكتوبر', 'تجاري', 85427924, 103882, 131);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'اكتوبر', 'زراعي', 19154600, 793435, 40);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'نوفمبر', 'سكني', 459234083, 543827, 951);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'نوفمبر', 'تجاري', 147999379, 323822, 108);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'نوفمبر', 'زراعي', 10545000, 1888820, 26);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ديسمبر', 'سكني', 603953419, 777630, 1235);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ديسمبر', 'تجاري', 260287313, 107912, 121);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (3, 'منطقة المدينة المنورة', 'ديسمبر', 'زراعي', 85122580, 1342504, 21);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يناير', 'سكني', 337426085, 2998747, 1268);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يناير', 'تجاري', 59369395, 1716051, 128);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يناير', 'زراعي', 154044177, 14313831, 159);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'فبراير', 'سكني', 353912172, 928650, 1391);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'فبراير', 'تجاري', 58802312, 1047201, 138);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'فبراير', 'زراعي', 25567883, 6332195, 118);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مارس', 'سكني', 376346478, 1144207, 1408);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مارس', 'تجاري', 54673825, 864353, 119);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مارس', 'زراعي', 86385781, 11819049, 129);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ابريل', 'سكني', 366170734, 1132154, 1567);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ابريل', 'تجاري', 70654052, 839102, 159);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ابريل', 'زراعي', 41545437, 23092507, 154);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مايو', 'سكني', 367556941, 969930, 1301);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مايو', 'تجاري', 126481221, 528174, 144);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'مايو', 'زراعي', 33219760, 15326974, 191);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يونيو', 'سكني', 137568127, 430397, 570);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يونيو', 'تجاري', 32597616, 132048, 62);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يونيو', 'زراعي', 32658030, 2065470, 39);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يوليو', 'سكني', 335703538, 1482455, 1391);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يوليو', 'تجاري', 68132269, 505854, 140);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'يوليو', 'زراعي', 51894383, 11427946, 173);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اوغسطس', 'سكني', 193019860, 932904, 891);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اوغسطس', 'تجاري', 45286064, 782019, 97);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اوغسطس', 'زراعي', 32551535, 3469564, 71);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اوغسطس', 'صناعي', 415000, 606, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'سبتمبر', 'سكني', 265866867, 905490, 1273);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'سبتمبر', 'تجاري', 46863238, 283367, 121);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'سبتمبر', 'زراعي', 17824106, 4099764, 112);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اكتوبر', 'سكني', 599065294, 2484032, 1784);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اكتوبر', 'تجاري', 88668975, 247366, 166);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'اكتوبر', 'زراعي', 94605068, 15291896, 149);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'نوفمبر', 'سكني', 323847226, 1141716, 1353);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'نوفمبر', 'تجاري', 214124750, 645416, 107);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'نوفمبر', 'زراعي', 61929003, 11019279, 85);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ديسمبر', 'سكني', 375772989, 994696, 1691);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ديسمبر', 'تجاري', 93007097, 795141, 133);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (4, 'منطقة القصيم', 'ديسمبر', 'زراعي', 41822139, 7353642, 71);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يناير', 'سكني', 2386451123, 1483238, 2199);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يناير', 'تجاري', 1144339840, 811100, 417);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يناير', 'زراعي', 56095952, 1310119, 63);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'فبراير', 'سكني', 1537560310, 1350443, 2243);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'فبراير', 'تجاري', 492218036, 15376076, 356);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'فبراير', 'زراعي', 47380250, 9252771, 90);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مارس', 'سكني', 1735154491, 1437851, 2522);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مارس', 'تجاري', 346769561, 2098460, 388);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مارس', 'زراعي', 25675249, 4762756, 62);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مارس', 'صناعي', 2500000, 4500, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ابريل', 'سكني', 1409428887, 1551607, 2637);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ابريل', 'تجاري', 563374166, 515314, 408);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ابريل', 'زراعي', 61110085, 7895077, 77);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ابريل', 'صناعي', 72588000, 47485, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مايو', 'سكني', 1356704010, 2739474, 2382);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مايو', 'تجاري', 407732404, 443220, 367);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'مايو', 'زراعي', 37521096, 3250653, 84);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يونيو', 'سكني', 503122983, 562510, 943);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يونيو', 'تجاري', 285797705, 213420, 161);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يونيو', 'زراعي', 17206942, 1414041, 33);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يونيو', 'صناعي', 10672400, 27908, 6);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يوليو', 'سكني', 1022099616, 1328550, 2275);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يوليو', 'تجاري', 368305748, 581988, 371);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'يوليو', 'زراعي', 44351137, 1555965, 71);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اوغسطس', 'سكني', 800187204, 923532, 1566);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اوغسطس', 'تجاري', 514820067, 410876, 200);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اوغسطس', 'زراعي', 17099000, 687658, 42);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'سبتمبر', 'سكني', 1211874326, 1281988, 2188);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'سبتمبر', 'تجاري', 503004972, 368858, 371);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'سبتمبر', 'زراعي', 30469411, 4923451, 58);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اكتوبر', 'سكني', 1519317210, 2331863, 3283);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اكتوبر', 'تجاري', 1190516786, 3174855, 532);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اكتوبر', 'زراعي', 76771408, 7729425, 84);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'اكتوبر', 'صناعي', 600000, 8994, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'نوفمبر', 'سكني', 1571015209, 1695524, 2981);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'نوفمبر', 'تجاري', 875841381, 3133776, 466);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'نوفمبر', 'زراعي', 20831829, 1735947, 35);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ديسمبر', 'سكني', 1706124648, 2063097, 3608);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ديسمبر', 'تجاري', 642402581, 1632080, 565);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (5, 'المنطقة الشرقية', 'ديسمبر', 'زراعي', 26708941, 2754368, 32);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يناير', 'سكني', 236413061, 426235, 644);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يناير', 'تجاري', 26639188, 46070, 65);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يناير', 'زراعي', 8157743, 470509, 36);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'فبراير', 'سكني', 253131265, 481459, 680);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'فبراير', 'تجاري', 24677195, 65637, 72);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'فبراير', 'زراعي', 15205740, 555363, 51);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مارس', 'سكني', 320037273, 677554, 920);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مارس', 'تجاري', 30205098, 70876, 72);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مارس', 'زراعي', 9410000, 538437, 42);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ابريل', 'سكني', 292500944, 597604, 864);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ابريل', 'تجاري', 43097192, 184297, 99);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ابريل', 'زراعي', 30141000, 1017349, 48);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مايو', 'سكني', 315510070, 669871, 818);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مايو', 'تجاري', 49225486, 80730, 95);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'مايو', 'زراعي', 16699790, 649859, 102);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يونيو', 'سكني', 107007297, 219632, 293);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يونيو', 'تجاري', 13836000, 8386, 13);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يونيو', 'زراعي', 5999000, 193686, 38);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يوليو', 'سكني', 310541885, 631510, 998);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يوليو', 'تجاري', 59424754, 114024, 129);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'يوليو', 'زراعي', 9289166, 895572, 62);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اوغسطس', 'سكني', 162140003, 401093, 547);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اوغسطس', 'تجاري', 20963450, 39984, 59);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اوغسطس', 'زراعي', 10037743, 649358, 32);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'سبتمبر', 'سكني', 210790555, 450971, 618);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'سبتمبر', 'تجاري', 33490897, 51825, 67);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'سبتمبر', 'زراعي', 8752000, 660439, 47);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اكتوبر', 'سكني', 300779379, 676482, 996);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اكتوبر', 'تجاري', 35043293, 75349, 97);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'اكتوبر', 'زراعي', 6630000, 764737, 47);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'نوفمبر', 'سكني', 277774099, 663132, 938);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'نوفمبر', 'تجاري', 33578318, 112608, 101);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'نوفمبر', 'زراعي', 8003000, 794605, 47);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ديسمبر', 'سكني', 375239054, 860293, 1232);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ديسمبر', 'تجاري', 41740644, 180451, 107);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (6, 'منطقة عسير', 'ديسمبر', 'زراعي', 9028613, 584591, 47);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يناير', 'سكني', 60501010, 113062, 183);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يناير', 'تجاري', 52021723, 90161, 127);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يناير', 'زراعي', 2403442, 639211, 38);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'فبراير', 'سكني', 98867380, 201446, 275);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'فبراير', 'تجاري', 49733931, 97476, 149);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'فبراير', 'زراعي', 3927834, 560284, 26);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مارس', 'سكني', 79698142, 160923, 271);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مارس', 'تجاري', 69617670, 197802, 187);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مارس', 'زراعي', 3894000, 3110812, 33);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ابريل', 'سكني', 76493604, 170004, 255);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ابريل', 'تجاري', 81244970, 199521, 221);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ابريل', 'زراعي', 10801833, 7843886, 66);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مايو', 'سكني', 86186504, 169031, 263);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مايو', 'تجاري', 277592115, 126316, 143);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'مايو', 'زراعي', 19881000, 5945530, 51);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يونيو', 'سكني', 26642311, 84831, 136);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يونيو', 'تجاري', 25485344, 38504, 56);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يونيو', 'زراعي', 1760000, 281775, 8);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يوليو', 'سكني', 61424671, 162106, 259);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يوليو', 'تجاري', 63579563, 184204, 177);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'يوليو', 'زراعي', 3717333, 2519453, 23);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اوغسطس', 'سكني', 38290420, 80141, 126);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اوغسطس', 'تجاري', 20268676, 44879, 64);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اوغسطس', 'زراعي', 976000, 297969, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'سبتمبر', 'سكني', 62253978, 140400, 229);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'سبتمبر', 'تجاري', 35166662, 76168, 113);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'سبتمبر', 'زراعي', 1660000, 390695, 21);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اكتوبر', 'سكني', 82306819, 180850, 294);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اكتوبر', 'تجاري', 53900075, 159487, 164);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'اكتوبر', 'زراعي', 4091533, 2895673, 34);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'نوفمبر', 'سكني', 73476013, 212867, 302);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'نوفمبر', 'تجاري', 63741532, 235938, 205);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'نوفمبر', 'زراعي', 6090000, 1087514, 15);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ديسمبر', 'سكني', 137124885, 358731, 543);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ديسمبر', 'تجاري', 100666445, 208067, 307);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (7, 'منطقة تبوك', 'ديسمبر', 'زراعي', 15409109, 4404446, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يناير', 'سكني', 251225269, 417532, 676);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يناير', 'تجاري', 56316733, 148543, 92);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يناير', 'زراعي', 10444776, 14284260, 159);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'فبراير', 'سكني', 222399044, 370366, 571);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'فبراير', 'تجاري', 18128684, 46546, 53);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'فبراير', 'زراعي', 12290343, 14542492, 160);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مارس', 'سكني', 156995743, 410466, 574);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مارس', 'تجاري', 17438312, 299601, 66);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مارس', 'زراعي', 14732373, 17721090, 191);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ابريل', 'سكني', 149219219, 437230, 669);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ابريل', 'تجاري', 10312524, 131644, 64);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ابريل', 'زراعي', 12846750, 8740487, 221);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مايو', 'سكني', 150218622, 518342, 581);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مايو', 'تجاري', 21456862, 482275, 76);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'مايو', 'زراعي', 22958234, 21048717, 191);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يونيو', 'سكني', 69239961, 148350, 249);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يونيو', 'تجاري', 8702129, 228527, 26);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يونيو', 'زراعي', 6958300, 6353402, 74);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يوليو', 'سكني', 141067389, 369818, 600);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يوليو', 'تجاري', 17762082, 189287, 67);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'يوليو', 'زراعي', 14012575, 7504890, 212);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اوغسطس', 'سكني', 99189547, 276208, 418);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اوغسطس', 'تجاري', 8594275, 33945, 43);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اوغسطس', 'زراعي', 6384367, 4737200, 118);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'سبتمبر', 'سكني', 134911742, 494678, 608);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'سبتمبر', 'تجاري', 15393261, 364973, 78);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'سبتمبر', 'زراعي', 20282743, 13511257, 230);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اكتوبر', 'سكني', 176495425, 776900, 812);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اكتوبر', 'تجاري', 19262986, 363900, 81);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'اكتوبر', 'زراعي', 16037527, 15837599, 206);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'نوفمبر', 'سكني', 177701296, 463177, 746);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'نوفمبر', 'تجاري', 19295674, 57361, 80);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'نوفمبر', 'زراعي', 11079962, 14222456, 64);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ديسمبر', 'سكني', 209697217, 1101950, 933);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ديسمبر', 'تجاري', 20749500, 64679, 85);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (8, 'منطقة حائل', 'ديسمبر', 'زراعي', 7642590, 9498894, 45);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يناير', 'سكني', 73288588, 313405, 440);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يناير', 'تجاري', 8896503, 36711, 53);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يناير', 'زراعي', 95000, 139200, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'فبراير', 'سكني', 78578452, 420868, 609);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'فبراير', 'تجاري', 5552653, 22805, 34);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'مارس', 'سكني', 92669384, 527947, 760);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'مارس', 'تجاري', 14291890, 50990, 73);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ابريل', 'سكني', 98785296, 460132, 668);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ابريل', 'تجاري', 8983303, 38493, 58);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ابريل', 'زراعي', 97000, 139200, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'مايو', 'سكني', 78161245, 355174, 526);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'مايو', 'تجاري', 10721046, 34509, 49);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'مايو', 'زراعي', 50000, 52500, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يونيو', 'سكني', 33227078, 152094, 219);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يونيو', 'تجاري', 6160950, 25641, 34);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يونيو', 'زراعي', 10000, 50000, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يوليو', 'سكني', 56435460, 346293, 503);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يوليو', 'تجاري', 12288503, 46535, 63);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'يوليو', 'زراعي', 194000, 200000, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اوغسطس', 'سكني', 48398792, 257688, 377);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اوغسطس', 'تجاري', 16435158, 888988, 43);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اوغسطس', 'زراعي', 60000, 50000, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'سبتمبر', 'سكني', 65275897, 387007, 570);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'سبتمبر', 'تجاري', 9393800, 38881, 57);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'سبتمبر', 'زراعي', 20000, 56000, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اكتوبر', 'سكني', 96486646, 510853, 735);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اكتوبر', 'تجاري', 14873629, 54269, 71);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'اكتوبر', 'زراعي', 220000, 165000, 3);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'نوفمبر', 'سكني', 74864728, 400480, 594);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'نوفمبر', 'تجاري', 11987875, 41927, 56);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'نوفمبر', 'زراعي', 100000, 50000, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ديسمبر', 'سكني', 92128498, 502983, 734);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ديسمبر', 'تجاري', 8604642, 32691, 47);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (9, 'منطقة الحدود الشمالية', 'ديسمبر', 'زراعي', 180000, 129500, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يناير', 'سكني', 59663727, 196533, 228);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يناير', 'تجاري', 33535730, 103931, 22);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يناير', 'زراعي', 6925022, 321682, 12);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'فبراير', 'سكني', 62002342, 183327, 275);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'فبراير', 'تجاري', 21095793, 55579, 28);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'فبراير', 'زراعي', 9484000, 177776, 11);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مارس', 'سكني', 64488965, 202981, 256);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مارس', 'تجاري', 15209000, 30574, 27);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مارس', 'زراعي', 2715000, 123413, 9);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ابريل', 'سكني', 76521737, 174958, 259);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ابريل', 'تجاري', 21300037, 34817, 24);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ابريل', 'زراعي', 9044250, 269860, 14);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مايو', 'سكني', 85807104, 449745, 278);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مايو', 'تجاري', 6734975, 20108, 15);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'مايو', 'زراعي', 6573145, 660366, 20);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يونيو', 'سكني', 30553083, 62179, 108);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يونيو', 'تجاري', 4758000, 4143, 7);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يونيو', 'زراعي', 1390000, 66265, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يوليو', 'سكني', 85012856, 267717, 289);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يوليو', 'تجاري', 8448000, 15078, 16);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'يوليو', 'زراعي', 6140000, 289394, 19);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اوغسطس', 'سكني', 38831477, 135480, 154);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اوغسطس', 'تجاري', 1495000, 2643, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اوغسطس', 'زراعي', 3140000, 93676, 5);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'سبتمبر', 'سكني', 65583879, 139010, 223);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'سبتمبر', 'تجاري', 7030000, 16284, 14);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'سبتمبر', 'زراعي', 6406742, 145166, 5);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اكتوبر', 'سكني', 95092021, 328893, 445);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اكتوبر', 'تجاري', 21595650, 54435, 41);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'اكتوبر', 'زراعي', 9275000, 322806, 13);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'نوفمبر', 'سكني', 84195166, 214121, 335);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'نوفمبر', 'تجاري', 80319500, 194215, 31);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'نوفمبر', 'زراعي', 2640000, 114149, 13);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ديسمبر', 'سكني', 101886709, 221101, 376);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ديسمبر', 'تجاري', 12768000, 107603, 39);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (10, 'منطقة جازان', 'ديسمبر', 'زراعي', 6866950, 890588, 11);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يناير', 'سكني', 46001460, 226255, 301);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يناير', 'تجاري', 6868000, 85508, 38);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يناير', 'زراعي', 2450000, 362783, 17);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'فبراير', 'سكني', 48855622, 218591, 285);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'فبراير', 'تجاري', 8874865, 33022, 42);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'فبراير', 'زراعي', 2924900, 291444, 13);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مارس', 'سكني', 40525685, 228978, 300);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مارس', 'تجاري', 13531500, 49141, 58);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مارس', 'زراعي', 18554000, 750272, 36);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ابريل', 'سكني', 31913422, 232428, 244);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ابريل', 'تجاري', 6809045, 50731, 52);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ابريل', 'زراعي', 9067000, 381066, 29);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مايو', 'سكني', 30613891, 167954, 200);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مايو', 'تجاري', 6687000, 67134, 49);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'مايو', 'زراعي', 4525000, 377629, 18);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يونيو', 'سكني', 13536019, 71235, 97);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يونيو', 'تجاري', 775000, 6972, 7);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يونيو', 'زراعي', 965000, 286220, 8);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يوليو', 'سكني', 29774972, 184345, 259);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يوليو', 'تجاري', 6740000, 55246, 40);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'يوليو', 'زراعي', 3855000, 530871, 25);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اوغسطس', 'سكني', 18870831, 121755, 160);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اوغسطس', 'تجاري', 4047000, 27294, 31);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اوغسطس', 'زراعي', 10511000, 461481, 25);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'سبتمبر', 'سكني', 24455000, 140083, 209);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'سبتمبر', 'تجاري', 6019385, 87226, 33);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'سبتمبر', 'زراعي', 8320000, 654912, 30);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اكتوبر', 'سكني', 41491852, 229719, 281);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اكتوبر', 'تجاري', 10539500, 34249, 43);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'اكتوبر', 'زراعي', 7420000, 506801, 16);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'نوفمبر', 'سكني', 30072321, 198825, 254);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'نوفمبر', 'تجاري', 6846800, 25888, 37);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'نوفمبر', 'زراعي', 8885000, 417065, 12);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ديسمبر', 'سكني', 45603912, 249023, 317);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ديسمبر', 'تجاري', 6822000, 58207, 44);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (11, 'منطقة نجران', 'ديسمبر', 'زراعي', 7850700, 436439, 13);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يناير', 'سكني', 17412698, 73252, 95);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يناير', 'تجاري', 3568000, 6400, 7);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يناير', 'زراعي', 950000, 19753, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'فبراير', 'سكني', 14477477, 45431, 57);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'فبراير', 'تجاري', 2001400, 30994, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'فبراير', 'زراعي', 50000, 967, 1);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مارس', 'سكني', 14498231, 60534, 69);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مارس', 'تجاري', 352000, 1751, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مارس', 'زراعي', 1515000, 8844, 3);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ابريل', 'سكني', 17674924, 76886, 90);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ابريل', 'تجاري', 635000, 3158, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ابريل', 'زراعي', 2499000, 126017, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مايو', 'سكني', 14092831, 49813, 63);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مايو', 'تجاري', 1190000, 2700, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'مايو', 'زراعي', 680000, 33809, 5);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يونيو', 'سكني', 5330000, 14524, 18);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يونيو', 'تجاري', 850000, 2394, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يونيو', 'زراعي', 480000, 6790, 2);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يوليو', 'سكني', 17874230, 113900, 99);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يوليو', 'تجاري', 465000, 2474, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'يوليو', 'زراعي', 965000, 86814, 5);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'اوغسطس', 'سكني', 14626966, 142102, 83);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'اوغسطس', 'زراعي', 2677000, 30424, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'سبتمبر', 'سكني', 14625115, 103323, 99);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'سبتمبر', 'تجاري', 780000, 3157, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'سبتمبر', 'زراعي', 1444866, 28177, 8);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'اكتوبر', 'سكني', 26063023, 110392, 104);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'اكتوبر', 'تجاري', 652000, 5523, 6);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'اكتوبر', 'زراعي', 320000, 15204, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'نوفمبر', 'سكني', 18347516, 80579, 91);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'نوفمبر', 'تجاري', 315000, 2172, 3);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'نوفمبر', 'زراعي', 2165000, 61526, 11);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ديسمبر', 'سكني', 16685547, 81028, 98);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ديسمبر', 'تجاري', 1145600, 6999, 6);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (12, 'منطقة الباحة', 'ديسمبر', 'زراعي', 940000, 50454, 10);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يناير', 'سكني', 63053108, 138383, 205);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يناير', 'تجاري', 6312856, 39781, 27);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يناير', 'زراعي', 1375000, 166554, 3);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'فبراير', 'سكني', 76113023, 173442, 254);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'فبراير', 'تجاري', 7187249, 24920, 30);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'فبراير', 'زراعي', 8615173, 666558, 14);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مارس', 'سكني', 96374918, 238798, 352);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مارس', 'تجاري', 15147287, 116553, 54);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مارس', 'زراعي', 6063438, 961501, 19);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ابريل', 'سكني', 83503510, 266563, 324);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ابريل', 'تجاري', 7658611, 79117, 37);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ابريل', 'زراعي', 7884678, 1024157, 15);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مايو', 'سكني', 60439180, 143443, 213);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مايو', 'تجاري', 15214522, 20768, 29);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'مايو', 'زراعي', 2524000, 500827, 8);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يونيو', 'سكني', 38068860, 90170, 143);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يونيو', 'تجاري', 5238292, 64302, 22);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يونيو', 'زراعي', 585000, 94597, 4);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يوليو', 'سكني', 51930159, 160830, 252);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يوليو', 'تجاري', 5852667, 21471, 33);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'يوليو', 'زراعي', 3568886, 536183, 14);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اوغسطس', 'سكني', 43480588, 146088, 223);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اوغسطس', 'تجاري', 4737001, 12297, 20);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اوغسطس', 'زراعي', 865000, 3141310, 6);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'سبتمبر', 'سكني', 56258883, 292994, 259);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'سبتمبر', 'تجاري', 5089557, 133072, 38);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'سبتمبر', 'زراعي', 3976928, 2813500, 17);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اكتوبر', 'سكني', 76312821, 241475, 364);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اكتوبر', 'تجاري', 5937378, 79348, 46);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'اكتوبر', 'زراعي', 8356100, 5151811, 26);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'نوفمبر', 'سكني', 68669497, 199578, 300);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'نوفمبر', 'تجاري', 14079443, 77356, 40);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'نوفمبر', 'زراعي', 8814500, 13333199, 18);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ديسمبر', 'سكني', 87318970, 287517, 449);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ديسمبر', 'تجاري', 8668799, 32694, 49);
INSERT INTO realestate (region_id, region_name, month, property_type, price_sar, area_sqm, transaction_count) VALUES (13, 'منطقة الجوف', 'ديسمبر', 'زراعي', 3260000, 1206992, 19);
